sudo: false #use container based infrastructure
language: node_js
node_js:
  - "5.4.1"

addons:
  apt:
    sources:
      - libnotify-bin

cache:
  directories:
    - node_modules

install:
  - travis_retry npm install -g gulp
  - travis_retry npm install

script:
  - npm test

after_script:
  - gulp coveralls
