sudo: false #use container based infrastructure
language: node_js
node_js:
  - "0.12"

addons:
  apt:
    sources:
      - libnotify-bin

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - nvm install 5.4.0 && nvm use 5.4.0 && npm install -g npm

install:
  - travis_retry npm install -g gulp
  - travis_retry npm install

script:
  - gulp test

after_script:
  - gulp coveralls
